keycloak:
  realm: 'master'
  auth-server-url: 'http://keycloak.nas-parrot.synology.me/auth'
  ssl-required: 'external'
  resource: 'login-app'
  credentials:
    secret: '1f1747ad-a018-452c-aa0d-094a3596d602'
  use-resource-role-mappings: true
  confidential-port: 0
  verify-token-audience: true

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false